<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="QuestPDF" Version="2025.*" />
    <PackageReference Include="ClosedXML" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransTrack.Core\TransTrack.Core.csproj" />
    <ProjectReference Include="..\TransTrack.Data\TransTrack.Data.csproj" />
  </ItemGroup>

</Project>
